DROP TABLE TESTUSER CASCADE CONSTRAINTS;

CREATE TABLE TESTUSER
(
  ID    VARCHAR2(15 BYTE),
  NAME  VARCHAR2(50 BYTE),
  AGE   NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;